### ISSUE TITLE
Pressing home or power twice causes apps to become slow with choppy sound

### ISSUE THREAD

**Issue by rsn8887** [switchbrew/nx-hbloader#15]
- Start a homebrew game as application. Ideally one with sound because it makes it easier to notice the problem.
- Press home to go to the menu
- Press home again to return from the menu to the app.
- Observe slow fps and choppy sound

The same happens when pressing the power button to sleep, and pressing the power button again to wake up. Using the power button, the problem happens with applets launched via album, too.

**Comment by fincs** [comment]
Seems to me like a problem with the homebrew apps themselves. Which apps have issues? If they're based on SDL; then this issue should be [reported there](https://github.com/devkitPro/SDL/issues).

**Comment by yellows8** [comment]
Can you try non-SDL apps for this?

**Comment by rsn8887** [comment]
I tried Retroarch and it doesn’t show the issue

**Comment by yellows8** [comment]
RA has handling for this.

**Comment by rsn8887** [comment]
So you mean the audio problems mentioned here have been fixed somehow:

https://github.com/switchbrew/libnx/pull/201#issuecomment-436737946 ?

Because the way I understand it, Retroarch "handles" this is by simply disabling suspend to prevent audio problems on resume. But it shouldn't be necessary to disable suspend.

**Comment by yellows8** [comment]
Not sure if using audren instead would help.

**Comment by yellows8** [comment]
Try the audio examples from switch-examples.

**Comment by rsn8887** [comment]
Hmm, the audio examples work fine. Well, the echo example is always distorted/choppy but that is regardless of the suspend/resume history. It might be my microphone (builtin mic on Apple earbuds).

Do they use threaded audio though? I remember in the Retroarch comments it was specifically mentioned threaded audio only as the problem. And SDL uses threaded audio, too.

**Comment by yellows8** [comment]
"Do they use threaded audio though?" No, see source.

**Comment by rsn8887** [comment]
To quote @natinusula on Discord:
[1:18 AM] natinusala: Suspend is the action of freezing the process whenever it is out of focus (HOME menu active or sleep)
[1:18 AM] natinusala: What kills audio is suspending the process
[1:19 AM] natinusala: So as a workaround you use the focus mode where the process isn't suspended when out of focus
[1:19 AM] natinusala: And use the applet hook to pause the game when that happens
[1:20 AM] natinusala: This is supposedly an issue with libnx, I think they acknowledged it

Has this really been acknowledged as an issue? Shall I re-open the issue in libnx repo?

**Comment by fincs** [comment]
It's not an issue with libnx. libnx is not responsible for what users do when calling its functions. Focus mode exists in applet for a reason - to allow applications to perform any necessary cleanup operations during a suspend or exit event - otherwise the system will freeze or kill the application process, which as you see can have unwanted consequences.

**Comment by rsn8887** [comment]
But I want my application to be frozen on suspend. I just don't understand why that causes threaded audio (e.g. all audio in SDL) to become choppy as soon as the application is unfrozen.

**Comment by fincs** [comment]
Precisely what I'm trying to say is that it is not possible to do anything to solve the problem as long as the focus mode isn't changed because the OS suspends the application without notifying it. Hence, probably SDL needs to be updated to change the focus mode and add an applet hook to wind down the audio streaming process during suspend; or explore alternative options (such as using audren).
